[project]
name = "cmu-housing"
revision = "1.0"

[providers]
local = "dotenv://.env"
vault = "vault://secrets.scottylabs.org/secret"

[profiles.ci.defaults]
required = false

[profiles.default]
LORE = { description = "Essential CMU Housing lore", required = false }

[profiles.prod]
SENTRY_DSN = { description = "Sentry DSN for error reporting", required = false }

[profiles.staging]

[profiles.preview]

[profiles.dev.defaults]
providers = ["vault"]

[profiles.dev]

