[project]
name = "cmu-housing"
revision = "1.0"

[profiles.ci.defaults]
required = false

[profiles.default]
LORE = { description = "Essential CMU Housing lore" }

[profiles.prod]
SENTRY_DSN = { description = "Sentry DSN for error reporting", required = false }

[profiles.staging]

[profiles.preview]

[profiles.dev]

