---
name: Task (leadership)
description: (leadership) Standard CMUHousing Development issue
title: "[BRIEF DESCRIPTION]"
labels: []
body:
  - type: textarea
    id: objective
    attributes:
      label: Overall Objective
      description:
        What is this issue trying to accomplish and why? If applicable
        where does the project stand right now?
      placeholder: e.g. Users currently see stale data because the cache isn't
        invalidated on update. This issue fixes that.
    validations:
      required: true
  - type: textarea
    id: approach
    attributes:
      label: Suggested Approach
      description:
        What might be a good direction to go down or what might be good
        resources/ideas to start from
      placeholder: |
        1. Use X to do Y
        2. I suggest looking up the docs for X
        3. Think about how to X
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Help & Resources
        - [README](https://github.com/ScottyLabs/cmuhousing/blob/main/README.md)
        - [Contributing Guidelines](https://github.com/ScottyLabs/cmuhousing/blob/main/CONTRIBUTING.md)
  - type: dropdown
    id: size
    attributes:
      label: Size
      description: Rough effort estimate of issue size
      options:
        - XS
        - S
        - M
        - L
        - XL
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Ready
        - In progress
        - Backlog
        - Done
    validations:
      required: true
  - type: checkboxes
    id: label
    attributes:
      label: Label
      options:
        - label: bug
        - label: enhancement
        - label: chore
        - label: good first issue
        - label: documentation
        - label: wontfix
    validations:
      required: true
