/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiMePreferences"];
    put: operations["putApiMePreferences"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiAuthLogin"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiAuthCallback"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiAuthLogout"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getApiMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getApiHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  getApiMePreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string | number;
            userId: string | number;
            accommodations: (string[] | null) | null;
            cookingFrequency: ((string | number) | null) | null;
            goals: (string[] | null) | null;
            gymFrequency: ((string | number) | null) | null;
            major: (string | null) | null;
            needsAloneTime: ((string | number) | null) | null;
            preferredAmenities: (string[] | null) | null;
            preferredGenderHousing: (string | null) | null;
            productiveAroundOthers: ((string | number) | null) | null;
            socialFrequency: ((string | number) | null) | null;
            updatedAt: ((Record<string, never> | string | number) | null) | null;
            year: (string | null) | null;
          } | null;
        };
      };
      /** @description Response for status 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  putApiMePreferences: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          accommodations?: (string[] | null) | null;
          cookingFrequency?: ((string | number) | null) | null;
          goals?: (string[] | null) | null;
          gymFrequency?: ((string | number) | null) | null;
          major?: (string | null) | null;
          needsAloneTime?: ((string | number) | null) | null;
          preferredAmenities?: (string[] | null) | null;
          preferredGenderHousing?: (string | null) | null;
          productiveAroundOthers?: ((string | number) | null) | null;
          socialFrequency?: ((string | number) | null) | null;
          year?: (string | null) | null;
        };
        "application/x-www-form-urlencoded": {
          accommodations?: (string[] | null) | null;
          cookingFrequency?: ((string | number) | null) | null;
          goals?: (string[] | null) | null;
          gymFrequency?: ((string | number) | null) | null;
          major?: (string | null) | null;
          needsAloneTime?: ((string | number) | null) | null;
          preferredAmenities?: (string[] | null) | null;
          preferredGenderHousing?: (string | null) | null;
          productiveAroundOthers?: ((string | number) | null) | null;
          socialFrequency?: ((string | number) | null) | null;
          year?: (string | null) | null;
        };
        "multipart/form-data": {
          accommodations?: (string[] | null) | null;
          cookingFrequency?: ((string | number) | null) | null;
          goals?: (string[] | null) | null;
          gymFrequency?: ((string | number) | null) | null;
          major?: (string | null) | null;
          needsAloneTime?: ((string | number) | null) | null;
          preferredAmenities?: (string[] | null) | null;
          preferredGenderHousing?: (string | null) | null;
          productiveAroundOthers?: ((string | number) | null) | null;
          socialFrequency?: ((string | number) | null) | null;
          year?: (string | null) | null;
        };
      };
    };
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string | number;
            userId: string | number;
            accommodations: (string[] | null) | null;
            cookingFrequency: ((string | number) | null) | null;
            goals: (string[] | null) | null;
            gymFrequency: ((string | number) | null) | null;
            major: (string | null) | null;
            needsAloneTime: ((string | number) | null) | null;
            preferredAmenities: (string[] | null) | null;
            preferredGenderHousing: (string | null) | null;
            productiveAroundOthers: ((string | number) | null) | null;
            socialFrequency: ((string | number) | null) | null;
            updatedAt: ((Record<string, never> | string | number) | null) | null;
            year: (string | null) | null;
          };
        };
      };
      /** @description Response for status 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
  getApiAuthLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  getApiAuthCallback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  getApiAuthLogout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: never;
  };
  getApiMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            id: string | number;
            name: string;
            andrewId: string;
            oidcSubject: string;
            createdTime: Record<string, never> | string | number;
          };
        };
      };
      /** @description Response for status 401 */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            error: string;
          };
        };
      };
    };
  };
}
